### ISSUE TITLE
New feature "image search" working wrong on Windows

### ISSUE THREAD

**Issue by mcvendrell** [yomybaby/atom-titanium#39]
Hi Yomy.

The last amazing feature you introduced is not working right on Windows. It offers always the full path to the image, instead the relative, e.g.:

*C:\appc\EPOC\app\assets\images\start.png*

instead

*/images/start.png*

**Comment by yomybaby** [comment]
Thanks for letting me know.

I have not tested this feature on Windows, because I use OS X only. 😉 
But, After you report this issue I found why it doesn't work properly on Windows.

https://github.com/yomybaby/atom-titanium/blob/master/lib/alloyCompletionRules.coffee#L69
```
text: '/'+file.replace(assetPath+'/','')
```

This month I have a tough time because busy.
If you make PR, that is the BEST!
If not, please wait for some time.

**Comment by mcvendrell** [comment]
I'd be happy to do it if I knew what to do to fix the problem. :)
But I'm lost. :(

**Comment by yomybaby** [comment]
I changed server part related generating path for Win32.
@mcvendrell , please let me know whether it work or not. :)

**Comment by mcvendrell** [comment]
It is working perfectly. THAAAAAANKSSS. :+1:
