### ISSUE TITLE
Make space between new generated style and controller method

### ISSUE THREAD

**Issue by hansemannn** [yomybaby/atom-titanium#56]
Hey @yomybaby,

would be nice to generate new TSS styles with a space (new line) between the brackets:
Before:
```js
"#myStyle": {
}
```
After:
```js
"#myStyle": {

}
```

It's a really really minor change, so maybe you can check it in between other stuff you work on. Thanks man!

*EDIT*: Same for controller methods:

Before:
```js
function doStuff(e) {
}
```
After:
```js
function doStuff(e) {

}
```

**Comment by yomybaby** [comment]
You can change generation template on package settings already. 😄 

Check this out  previous releases note: 
https://github.com/yomybaby/atom-titanium/releases/tag/v0.11.2

**Comment by hansemannn** [comment]
Sweet! What prevents you from making it default then? :)

**Comment by yomybaby** [comment]
There is two changes in your suggestion 
- Adding one space before colon : I'll make it default. Thanks :) 
- Adding one more new line between { and } : I considered this when I made a generating feature. But I didn't add. It though that pressing "cmd + enter" is better when you need new line. Because "cmd+enter" make a new line after current line and add auto-indent space even your cursor in the middle of line. (I ❤️ "cmd+enter" )

I know the best is :
  ```
  // _ is cursor position
  function doStuff(e) {
    _
  }
  ```
But I couldn't found a best way to add indent correctly(2 space or 4 space or tab) and to move cursor.
